# Nixpacks configuration for Railway deployment
[variables]
PYTHON_VERSION = "3.11"
PIP_CACHE_DIR = "/tmp/pip-cache"

[phases.build]
dependsOn = ["install"]
cmds = [
    "pip install --no-cache-dir --upgrade pip setuptools wheel",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.install]
aptPkgs = ["build-essential"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --loop uvloop --http httptools"

[staticAssets]
# No static assets for this MVP
